### ISSUE TITLE
Need to explain ssl here

### ISSUE THREAD

**Issue by dev-sandeepsingh** [uCreateit/chaos-monkey-dox#2]
On ` Register/Add domain name` in screen shot there is a button `Configure SSL`. But in my case its not there.This is because we need to need dynos

**Comment by jdecode** [comment]
@SandeepSinghUcreate - You can open a PR and submit the changes!

**Comment by dev-sandeepsingh** [comment]
Sure @jdecode

**Comment by jdecode** [comment]
@SandeepSinghUcreate  - I believe this was merged last week (via a PR).
If the required changes have been done, then please close this issue.

**Comment by dev-sandeepsingh** [comment]
Sure @jdecode
